//: arrays/E03_TwoDDoubleArray.java
/****************** Exercise 3 *****************
 * Write a method that creates and initializes a
 * two-dimensional array of double. The size of
 * the array is determined by the arguments of
 * the method, and the initialization values are
 * a range determined by beginning and ending
 * values that are also arguments of the method.
 * Create a second method that will print the
 * array generated by the first method. In main()
 * test the methods by creating and printing
 * several different sizes of arrays.
 378
 Thinking in Java, 4th Edition Annotated Solution Guide
 ***********************************************/
package arrays;

import java.util.Locale;

import static net.mindview.util.Print.print;


/****
 *
 *
 *
 * 437页
 *      编写一个方法，它接受一个int参数，并返回一个该尺寸的数组，用BerylliumSphere对象填充该
 *  数组
 *
 *
 *  1
 */
public class E03_TwoDDoubleArray {
    public static double[][] twoDDoubleArray(int xLen, int yLen, double valStart, double valEnd) {
        double[][] array = new double[xLen][yLen];
        double increment = (valEnd - valStart) / (xLen * yLen);
        double val = valStart;
        for (int i = 0; i < array.length; i++)
            for (int j = 0; j < array[i].length; j++) {
                array[i][j] = val;
                val += increment;
            }
        return array;
    }

    public static void printArray(double[][] array) {
        for (int i = 0; i < array.length; i++) {
            for (int j = 0; j < array[i].length; j++)
                System.out.printf(Locale.US, "%.2f ", array[i][j]);
            print();
        }
    }

    public static void main(String args[]) {
        double[][] twoD = twoDDoubleArray(4, 6, 47.0, 99.0);
        printArray(twoD);
        print("**********************");
        double[][] twoD2 = twoDDoubleArray(2, 2, 47.0, 99.0);
        printArray(twoD2);
        print("**********************");
        double[][] twoD3 = twoDDoubleArray(9, 5, 47.0, 99.0);
        printArray(twoD3);
    }
} 